### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by roaldarbol** [QuantStack/jupytercad#183]
Really looking forward to using JupyterCAD, looks like an amazing tool!

TL;DR: I made a clean install with `poetry`, but failed a couple of times along the way due to missing dependencies, so thought it would be useful to document (maybe they should be added as additional dependencies?). After each step I run `jupyter cad` - I've added the error messages for each step below:

<details>
<summary>1. After adding <code>jupyter_cad</code>: <code>jupyterlab_server</code> missing</summary>

```python
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-cad", line 5, in <module>
    from jupytercad.cadapp import main
  File "/usr/local/lib/python3.10/site-packages/jupytercad/__init__.py", line 2, in <module>
    from .cadapp import CadApp
  File "/usr/local/lib/python3.10/site-packages/jupytercad/cadapp/__init__.py", line 1, in <module>
    from .cadapp import CadApp, main  # noqa
  File "/usr/local/lib/python3.10/site-packages/jupytercad/cadapp/cadapp.py", line 10, in <module>
    from jupyterlab_server import LabServerApp
ModuleNotFoundError: No module named 'jupyterlab_server'
```
</details>

<details>
<summary>2. After adding <code>jupyterlab_server</code>: <code>jupyterlab</code> missing</summary>

```python
(jp-cad-py3.10) (base) ➜  jp-cad jupyter cad
[I 2023-06-04 12:22:15.530 ServerApp] Package jupytercad took 0.0000s to import
[I 2023-06-04 12:22:15.693 ServerApp] Package jupyter_collaboration took 0.1624s to import
[I 2023-06-04 12:22:15.694 ServerApp] Package jupyter_server_fileid took 0.0000s to import
[I 2023-06-04 12:22:15.741 ServerApp] Package jupyter_server_terminals took 0.0462s to import
[W 2023-06-04 12:22:15.743 ServerApp] jupyterlab | error adding extension (enabled: True): The module 'jupyterlab' could not be found (No module named 'jupyterlab'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 319, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 183, in __init__
        self._load_metadata()
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 198, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'jupyterlab' could not be found (No module named 'jupyterlab'). Are you sure the extension is installed?
[W 2023-06-04 12:22:15.744 ServerApp] nbclassic | error adding extension (enabled: True): The module 'nbclassic' could not be found (No module named 'nbclassic'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 319, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 183, in __init__
        self._load_metadata()
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 198, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'nbclassic' could not be found (No module named 'nbclassic'). Are you sure the extension is installed?
[W 2023-06-04 12:22:15.745 ServerApp] voila.server_extension | error adding extension (enabled: True): The module 'voila.server_extension' could not be found (No module named 'voila'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 319, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 183, in __init__
        self._load_metadata()
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 198, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'voila.server_extension' could not be found (No module named 'voila'). Are you sure the extension is installed?
[I 2023-06-04 12:22:15.756 ServerApp] jupyter_collaboration | extension was successfully linked.
[I 2023-06-04 12:22:15.785 ServerApp] jupyter_server_fileid | extension was successfully linked.
[I 2023-06-04 12:22:15.797 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-06-04 12:22:15.808 ServerApp] jupytercad | extension was successfully linked.
[I 2023-06-04 12:22:15.913 ServerApp] jupyter_collaboration | extension was successfully loaded.
[I 2023-06-04 12:22:15.913 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2023-06-04 12:22:15.914 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /Users/roaldarbol/Filen/git-projects/jp-cad
[I 2023-06-04 12:22:15.914 FileIdExtension] ArbitraryFileIdManager : Configured database path: /Users/roaldarbol/Library/Jupyter/file_id_manager.db
[I 2023-06-04 12:22:16.082 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2023-06-04 12:22:16.082 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2023-06-04 12:22:16.135 FileIdExtension] Attached event listeners.
[I 2023-06-04 12:22:16.135 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2023-06-04 12:22:16.137 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-06-04 12:22:16.162 ServerApp] jupytercad | extension was successfully loaded.
[I 2023-06-04 12:22:16.184 ServerApp] Serving notebooks from local directory: /Users/roaldarbol/Filen/git-projects/jp-cad
[I 2023-06-04 12:22:16.185 ServerApp] Jupyter Server 2.6.0 is running at:
[I 2023-06-04 12:22:16.185 ServerApp] http://localhost:8888/cad?token=cd98190d49aee207c93ae0f1b590a8b26c6af7fe6a553e68
[I 2023-06-04 12:22:16.185 ServerApp]     http://127.0.0.1:8888/cad?token=cd98190d49aee207c93ae0f1b590a8b26c6af7fe6a553e68
[I 2023-06-04 12:22:16.185 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-06-04 12:22:16.245 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///Users/roaldarbol/Library/Jupyter/runtime/jpserver-55614-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/cad?token=cd98190d49aee207c93ae0f1b590a8b26c6af7fe6a553e68
        http://127.0.0.1:8888/cad?token=cd98190d49aee207c93ae0f1b590a8b26c6af7fe6a553e68
[E 2023-06-04 12:22:17.960 ServerApp] Error unpacking user from cookie: Extra data: line 1 column 4 (char 3)
[E 2023-06-04 12:22:17.961 ServerApp] Error unpacking user from cookie: Extra data: line 1 column 4 (char 3)
[W 2023-06-04 12:22:19.004 ServerApp] 404 GET /lab/extensions/@jupytercad/jupytercad-extension/static/remoteEntry.ed192893ffeb37154379.js (4c54471e4af0484c89f61dd302edb31c@::1) 51.23ms referer=http://localhost:8888/cad
[W 2023-06-04 12:22:19.009 ServerApp] 404 GET /lab/extensions/@jupyter/collaboration-extension/static/remoteEntry.b7dd09e5b7cf57c2dbc6.js (4c54471e4af0484c89f61dd302edb31c@::1) 4.10ms referer=http://localhost:8888/cad
[W 2023-06-04 12:22:19.053 ServerApp] 404 GET /lab/api/settings?1685877739043 (4c54471e4af0484c89f61dd302edb31c@::1) 3.25ms referer=http://localhost:8888/cad
[W 2023-06-04 13:00:03.282 ServerApp] 404 GET /lab/extensions/@jupytercad/jupytercad-extension/static/remoteEntry.ed192893ffeb37154379.js (4c54471e4af0484c89f61dd302edb31c@::1) 3.06ms referer=http://localhost:8888/cad
[W 2023-06-04 13:00:03.286 ServerApp] 404 GET /lab/extensions/@jupyter/collaboration-extension/static/remoteEntry.b7dd09e5b7cf57c2dbc6.js (4c54471e4af0484c89f61dd302edb31c@::1) 4.14ms referer=http://localhost:8888/cad
[W 2023-06-04 13:00:03.358 ServerApp] 404 GET /lab/api/settings?1685880003328 (4c54471e4af0484c89f61dd302edb31c@::1) 2.55ms referer=http://localhost:8888/cad
[W 2023-06-04 13:00:16.414 ServerApp] 404 GET /lab/extensions/@jupytercad/jupytercad-extension/static/remoteEntry.ed192893ffeb37154379.js (4c54471e4af0484c89f61dd302edb31c@::1) 3.91ms referer=http://localhost:8888/cad
[W 2023-06-04 13:00:16.419 ServerApp] 404 GET /lab/extensions/@jupyter/collaboration-extension/static/remoteEntry.b7dd09e5b7cf57c2dbc6.js (4c54471e4af0484c89f61dd302edb31c@::1) 4.41ms referer=http://localhost:8888/cad
[W 2023-06-04 13:00:16.453 ServerApp] 404 GET /lab/api/settings?1685880016434 (4c54471e4af0484c89f61dd302edb31c@::1) 3.98ms referer=http://localhost:8888/cad
[W 2023-06-04 13:00:39.673 ServerApp] 404 GET /lab/extensions/@jupytercad/jupytercad-extension/static/remoteEntry.ed192893ffeb37154379.js (5a68f5419cfb4f0ea384e250df2c4970@127.0.0.1) 2.17ms referer=http://127.0.0.1:8888/cad
[W 2023-06-04 13:00:39.679 ServerApp] 404 GET /lab/extensions/@jupyter/collaboration-extension/static/remoteEntry.b7dd09e5b7cf57c2dbc6.js (5a68f5419cfb4f0ea384e250df2c4970@127.0.0.1) 2.64ms referer=http://127.0.0.1:8888/cad
[W 2023-06-04 13:00:39.725 ServerApp] 404 GET /lab/api/settings?1685880039704 (5a68f5419cfb4f0ea384e250df2c4970@127.0.0.1) 2.96ms referer=http://127.0.0.1:8888/cad
```
</details>

<details>
<summary>3. After adding <code>jupyterlab</code>: <code>nbclassic</code> missing</summary>

```python
(jp-cad-py3.10) (base) ➜  jp-cad jupyter cad
[I 2023-06-04 13:05:49.264 ServerApp] Package jupytercad took 0.0000s to import
[I 2023-06-04 13:05:49.321 ServerApp] Package jupyter_collaboration took 0.0567s to import
[I 2023-06-04 13:05:49.373 ServerApp] Package jupyter_lsp took 0.0514s to import
[W 2023-06-04 13:05:49.373 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-06-04 13:05:49.373 ServerApp] Package jupyter_server_fileid took 0.0000s to import
[I 2023-06-04 13:05:49.390 ServerApp] Package jupyter_server_terminals took 0.0160s to import
[I 2023-06-04 13:05:49.426 ServerApp] Package jupyterlab took 0.0358s to import
[W 2023-06-04 13:05:50.835 ServerApp] nbclassic | error adding extension (enabled: True): The module 'nbclassic' could not be found (No module named 'nbclassic'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 319, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 183, in __init__
        self._load_metadata()
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 198, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'nbclassic' could not be found (No module named 'nbclassic'). Are you sure the extension is installed?
[I 2023-06-04 13:05:50.836 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-06-04 13:05:50.836 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[W 2023-06-04 13:05:50.839 ServerApp] voila.server_extension | error adding extension (enabled: True): The module 'voila.server_extension' could not be found (No module named 'voila'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 319, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 183, in __init__
        self._load_metadata()
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 198, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'voila.server_extension' could not be found (No module named 'voila'). Are you sure the extension is installed?
[I 2023-06-04 13:05:50.849 ServerApp] jupyter_collaboration | extension was successfully linked.
[I 2023-06-04 13:05:50.849 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-06-04 13:05:50.855 ServerApp] jupyter_server_fileid | extension was successfully linked.
[I 2023-06-04 13:05:50.862 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-06-04 13:05:50.867 ServerApp] jupytercad | extension was successfully linked.
[I 2023-06-04 13:05:50.872 ServerApp] jupyterlab | extension was successfully linked.
[W 2023-06-04 13:05:57.060 ServerApp] voila.server_extension | error adding extension (enabled: True): The module 'voila.server_extension' could not be found (No module named 'voila'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 319, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 183, in __init__
        self._load_metadata()
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 198, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'voila.server_extension' could not be found (No module named 'voila'). Are you sure the extension is installed?
[I 2023-06-04 13:05:57.060 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-06-04 13:05:57.247 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-06-04 13:05:57.255 ServerApp] jupyter_collaboration | extension was successfully loaded.
[I 2023-06-04 13:05:57.260 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-06-04 13:05:57.261 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2023-06-04 13:05:57.263 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /Users/roaldarbol/Filen/git-projects/jp-cad
[I 2023-06-04 13:05:57.263 FileIdExtension] ArbitraryFileIdManager : Configured database path: /Users/roaldarbol/Library/Jupyter/file_id_manager.db
[I 2023-06-04 13:05:57.369 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2023-06-04 13:05:57.369 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2023-06-04 13:05:57.437 FileIdExtension] Attached event listeners.
[I 2023-06-04 13:05:57.437 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2023-06-04 13:05:57.440 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-06-04 13:05:57.445 ServerApp] jupytercad | extension was successfully loaded.
[I 2023-06-04 13:05:57.448 LabApp] JupyterLab extension loaded from /Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyterlab
[I 2023-06-04 13:05:57.448 LabApp] JupyterLab application directory is /Users/roaldarbol/Filen/git-projects/jp-cad/.venv/share/jupyter/lab
[I 2023-06-04 13:05:57.450 LabApp] Extension Manager is 'pypi'.
[I 2023-06-04 13:05:57.453 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-06-04 13:05:57.461 ServerApp] Serving notebooks from local directory: /Users/roaldarbol/Filen/git-projects/jp-cad
[I 2023-06-04 13:05:57.462 ServerApp] Jupyter Server 2.6.0 is running at:
[I 2023-06-04 13:05:57.462 ServerApp] http://localhost:8888/cad?token=532fc3f247ce72fa7de0996cb09abb651ecaf03af1a627c6
[I 2023-06-04 13:05:57.462 ServerApp]     http://127.0.0.1:8888/cad?token=532fc3f247ce72fa7de0996cb09abb651ecaf03af1a627c6
[I 2023-06-04 13:05:57.462 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-06-04 13:05:57.514 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///Users/roaldarbol/Library/Jupyter/runtime/jpserver-58235-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/cad?token=532fc3f247ce72fa7de0996cb09abb651ecaf03af1a627c6
        http://127.0.0.1:8888/cad?token=532fc3f247ce72fa7de0996cb09abb651ecaf03af1a627c6
[I 2023-06-04 13:06:04.918 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
```
</details>

<details>
<summary>4. After adding <code>nbclassic</code>: <b>IT WORKS</b> - but <code>voila</code> missing</summary>

```python
(jp-cad-py3.10) (base) ➜  jp-cad jupyter cad         
[I 2023-06-04 13:14:25.237 ServerApp] Package jupytercad took 0.0000s to import
[I 2023-06-04 13:14:25.283 ServerApp] Package jupyter_collaboration took 0.0453s to import
[I 2023-06-04 13:14:25.320 ServerApp] Package jupyter_lsp took 0.0364s to import
[W 2023-06-04 13:14:25.320 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-06-04 13:14:25.320 ServerApp] Package jupyter_server_fileid took 0.0000s to import
[I 2023-06-04 13:14:25.341 ServerApp] Package jupyter_server_terminals took 0.0197s to import
[I 2023-06-04 13:14:25.356 ServerApp] Package jupyterlab took 0.0137s to import
[I 2023-06-04 13:14:25.811 ServerApp] Package nbclassic took 0.0074s to import
[W 2023-06-04 13:14:25.818 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-06-04 13:14:25.819 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-06-04 13:14:25.819 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[W 2023-06-04 13:14:25.821 ServerApp] voila.server_extension | error adding extension (enabled: True): The module 'voila.server_extension' could not be found (No module named 'voila'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 319, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 183, in __init__
        self._load_metadata()
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 198, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'voila.server_extension' could not be found (No module named 'voila'). Are you sure the extension is installed?
[I 2023-06-04 13:14:25.831 ServerApp] jupyter_collaboration | extension was successfully linked.
[I 2023-06-04 13:14:25.831 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-06-04 13:14:25.841 ServerApp] jupyter_server_fileid | extension was successfully linked.
[I 2023-06-04 13:14:25.847 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-06-04 13:14:25.855 ServerApp] jupytercad | extension was successfully linked.
[I 2023-06-04 13:14:25.863 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-06-04 13:14:25.871 ServerApp] nbclassic | extension was successfully linked.
[W 2023-06-04 13:14:26.760 ServerApp] voila.server_extension | error adding extension (enabled: True): The module 'voila.server_extension' could not be found (No module named 'voila'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 319, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 183, in __init__
        self._load_metadata()
      File "/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyter_server/extension/manager.py", line 198, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'voila.server_extension' could not be found (No module named 'voila'). Are you sure the extension is installed?
[I 2023-06-04 13:14:26.760 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-06-04 13:14:26.841 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-06-04 13:14:26.846 ServerApp] jupyter_collaboration | extension was successfully loaded.
[I 2023-06-04 13:14:26.852 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-06-04 13:14:26.853 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2023-06-04 13:14:26.853 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /Users/roaldarbol/Filen/git-projects/jp-cad
[I 2023-06-04 13:14:26.853 FileIdExtension] ArbitraryFileIdManager : Configured database path: /Users/roaldarbol/Library/Jupyter/file_id_manager.db
[I 2023-06-04 13:14:26.854 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2023-06-04 13:14:26.854 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2023-06-04 13:14:26.855 FileIdExtension] Attached event listeners.
[I 2023-06-04 13:14:26.856 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2023-06-04 13:14:26.857 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-06-04 13:14:26.861 ServerApp] jupytercad | extension was successfully loaded.
[I 2023-06-04 13:14:26.863 LabApp] JupyterLab extension loaded from /Users/roaldarbol/Filen/git-projects/jp-cad/.venv/lib/python3.10/site-packages/jupyterlab
[I 2023-06-04 13:14:26.863 LabApp] JupyterLab application directory is /Users/roaldarbol/Filen/git-projects/jp-cad/.venv/share/jupyter/lab
[I 2023-06-04 13:14:26.864 LabApp] Extension Manager is 'pypi'.
[I 2023-06-04 13:14:26.879 ServerApp] jupyterlab | extension was successfully loaded.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                                                                           
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 2023-06-04 13:14:26.951 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-06-04 13:14:26.953 ServerApp] Serving notebooks from local directory: /Users/roaldarbol/Filen/git-projects/jp-cad
[I 2023-06-04 13:14:26.953 ServerApp] Jupyter Server 2.6.0 is running at:
[I 2023-06-04 13:14:26.953 ServerApp] http://localhost:8888/cad?token=9fa85750bf2b6c5a02b2226dd54a8828806cebff14f56a44
[I 2023-06-04 13:14:26.954 ServerApp]     http://127.0.0.1:8888/cad?token=9fa85750bf2b6c5a02b2226dd54a8828806cebff14f56a44
[I 2023-06-04 13:14:26.954 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-06-04 13:14:26.992 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///Users/roaldarbol/Library/Jupyter/runtime/jpserver-59764-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/cad?token=9fa85750bf2b6c5a02b2226dd54a8828806cebff14f56a44
        http://127.0.0.1:8888/cad?token=9fa85750bf2b6c5a02b2226dd54a8828806cebff14f56a44
[I 2023-06-04 13:14:30.725 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2023-06-04 13:14:36.138 ServerApp] Creating new file in 
```

</details>

<details>
<summary>5.  <code>voila</code> can't install</summary>

```python
(jp-cad-py3.10) (base) ➜  jp-cad poetry add voila     
Using version ^0.4.0 for voila

Updating dependencies
Resolving dependencies... (0.5s)

Because no versions of voila match >0.4.0,<0.5.0
 and voila (0.4.0) depends on jupyter-server (>=1.18,<2.0.0), voila (>=0.4.0,<0.5.0) requires jupyter-server (>=1.18,<2.0.0).
And because jupyterlab (4.0.1) depends on jupyter-server (>=2.4.0,<3)
 and no versions of jupyterlab match >4.0.1,<5.0.0, voila (>=0.4.0,<0.5.0) is incompatible with jupyterlab (>=4.0.1,<5.0.0).
So, because jp-cad depends on both jupyterlab (^4.0.1) and voila (^0.4.0), version solving failed.
```
</details>

**Comment by trungleduc** [comment]
Hi, can you try to install `JupyterCAD` with pip? All the dependencies should be installed automatically, I'm not a `peotry` user so I don't know if it reads the dependencies list of `JupyerCAD`

**Comment by roaldarbol** [comment]
`poetry` doesn't do anything special compared to `pip`, it uses PyPi to install as default. I get the same output with direct `pip install jupytercad` (`jupyter lab` works, the error appears for `jupyter cad`). I get:
```python
(base) ➜  ~ jupyter cad
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-cad", line 5, in <module>
    from jupytercad.cadapp import main
  File "/usr/local/lib/python3.10/site-packages/jupytercad/__init__.py", line 2, in <module>
    from .cadapp import CadApp
  File "/usr/local/lib/python3.10/site-packages/jupytercad/cadapp/__init__.py", line 1, in <module>
    from .cadapp import CadApp, main  # noqa
  File "/usr/local/lib/python3.10/site-packages/jupytercad/cadapp/cadapp.py", line 10, in <module>
    from jupyterlab_server import LabServerApp
ModuleNotFoundError: No module named 'jupyterlab_server'
```

From looking at the `pyproject.toml` file, `jupyterlab_server` is not there either, only `jupyter_server`. Where should the mentioned dependencies be mentioned?

**Comment by martinRenou** [comment]
>  After adding nbclassic: IT WORKS - but voila missing

JupyterCad does not need Voila, does it?

**Comment by trungleduc** [comment]
Fixed in 0.2.3

**Comment by roaldarbol** [comment]
Just did a clean re-install and works now on 0.2.3. 🥳

> JupyterCad does not need Voila, does it?

It seems to work without for sure, but still throws a warning - it seems to not impact performance, but I always get a bit nervous with any warnings thrown. ;-) And just FYI on 0.2.3 there are warnings for `nbclassic` and `voila`. The messages are the same as above.

**Comment by martinRenou** [comment]
It seems you have server extensions (nbclassic and voila) for jupyter that are lying around but the related Python modules are not installed. Can you show the output of `jupyter server extension list`?

You may be able to remove those warnings by running `jupyter server extension disable {extension}` for extensions that are faulty.

**Comment by roaldarbol** [comment]
Seems you're right about the competing installations... It seems to default back to the global installation (which came with Anaconda), even when I've got a `venv` installation. Here it first shows that it should use the `venv` installation, then I run `jupyter server extension list` which shows me a couple of different config dirs, and after that the chosen installation has changed. Really strange behaviour, but I reckon it's probably just a *me* issue - I'll try to figure it out. Thanks for your help though!

```python
(jp-cad-py3.10) (base) ➜  jp-cad which jupyter
/Users/roaldarbol/Filen/git-projects/jp-cad/.venv/bin/jupyter
(jp-cad-py3.10) (base) ➜  jp-cad jupyter server extension list
Config dir: /Users/roaldarbol/.jupyter

Config dir: /Users/roaldarbol/Filen/git-projects/jp-cad/.venv/etc/jupyter
    jupyter_lsp enabled
    - Validating jupyter_lsp...
Package jupyter_lsp took 0.1954s to import
A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      jupyter_lsp 2.2.0 OK
    jupyter_collaboration enabled
    - Validating jupyter_collaboration...
Package jupyter_collaboration took 6.2255s to import
      jupyter_collaboration 1.0.0 OK
    jupyter_server_fileid enabled
    - Validating jupyter_server_fileid...
Package jupyter_server_fileid took 0.0000s to import
      jupyter_server_fileid 0.9.0 OK
    jupyter_server_terminals enabled
    - Validating jupyter_server_terminals...
Package jupyter_server_terminals took 0.0902s to import
      jupyter_server_terminals 0.4.4 OK
    jupytercad enabled
    - Validating jupytercad...
Package jupytercad took 0.0000s to import
      jupytercad 0.2.3 OK
    jupyterlab enabled
    - Validating jupyterlab...
Package jupyterlab took 0.1014s to import
      jupyterlab 4.0.1 OK
    nbclassic enabled
    - Validating nbclassic...
Package nbclassic took 0.0038s to import
A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      nbclassic 1.0.0 OK
    notebook_shim enabled
    - Validating notebook_shim...
Package notebook_shim took 0.0000s to import
A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      notebook_shim  OK

Config dir: /usr/local/etc/jupyter
    jupyter_collaboration enabled
    - Validating jupyter_collaboration...
Package jupyter_collaboration took 0.0000s to import
      jupyter_collaboration 1.0.0 OK
    jupyter_server_fileid enabled
    - Validating jupyter_server_fileid...
Package jupyter_server_fileid took 0.0000s to import
      jupyter_server_fileid 0.9.0 OK
    jupyter_server_terminals enabled
    - Validating jupyter_server_terminals...
Package jupyter_server_terminals took 0.0001s to import
      jupyter_server_terminals 0.4.4 OK
    jupytercad enabled
    - Validating jupytercad...
Package jupytercad took 0.0001s to import
      jupytercad 0.2.3 OK
    jupyterlab enabled
    - Validating jupyterlab...
Package jupyterlab took 0.0002s to import
      jupyterlab 4.0.1 OK
    nbclassic enabled
    - Validating nbclassic...
Package nbclassic took 0.0000s to import
A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
      nbclassic 1.0.0 OK
    voila.server_extension enabled
    - Validating voila.server_extension...
       X The module 'voila.server_extension' could not be found (No module named 'voila'). Are you sure the extension is installed?

(jp-cad-py3.10) (base) ➜  jp-cad which jupyter                
/usr/local/anaconda3/bin/jupyter
```
